# chore: update Typo CI 
---

dictionaries:
  - en

excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "designsystem/build.gradle"

excluded_words:
  - CoreMatchers
  - Matchers
  - Natura
  - RootMatchers
  - ViewMatchers
  - androidx
  - appbar
  - appcompat
  - committed
  - dimen
  - dimens
  - drawables
  - enum
  - gradlew
  - hdpi
  - jimmyandrade
  - kotlinx
  - ldpi
  - mdpi
  - mockup
  - nat
  - natOnPrimary
  - natOnPrimaryDark
  - natOnPrimaryLight
  - natOnSecondary
  - natPrimary
  - natPrimaryDark
  - natPrimaryLight
  - natSecondary
  - natSecondaryDark
  - natSecondaryLight
  - natds-commons
  - natds-icons
  - natura
  - robolectric
  - typoci
  - xhdpi
  - xxhdpi
  - xxxhdpi

spellcheck_filenames: true
